// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "purchase.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {
class PurchaseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Purchase> {
} _Purchase_default_instance_;

namespace protobuf_purchase_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Purchase, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Purchase, claim_hash_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Purchase)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Purchase_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "purchase.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _Purchase_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Purchase_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\016purchase.proto\022\002pb\"\036\n\010Purchase\022\022\n\nclai"
      "m_hash\030\001 \001(\014B\004Z\002./b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 66);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "purchase.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_purchase_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Purchase::kClaimHashFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Purchase::Purchase()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_purchase_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.Purchase)
}
Purchase::Purchase(const Purchase& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  claim_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.claim_hash().size() > 0) {
    claim_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.claim_hash_);
  }
  // @@protoc_insertion_point(copy_constructor:pb.Purchase)
}

void Purchase::SharedCtor() {
  claim_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

Purchase::~Purchase() {
  // @@protoc_insertion_point(destructor:pb.Purchase)
  SharedDtor();
}

void Purchase::SharedDtor() {
  claim_hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Purchase::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Purchase::descriptor() {
  protobuf_purchase_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_purchase_2eproto::file_level_metadata[0].descriptor;
}

const Purchase& Purchase::default_instance() {
  protobuf_purchase_2eproto::InitDefaults();
  return *internal_default_instance();
}

Purchase* Purchase::New(::google::protobuf::Arena* arena) const {
  Purchase* n = new Purchase;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Purchase::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.Purchase)
  claim_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Purchase::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.Purchase)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes claim_hash = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_claim_hash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.Purchase)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.Purchase)
  return false;
#undef DO_
}

void Purchase::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.Purchase)
  // bytes claim_hash = 1;
  if (this->claim_hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->claim_hash(), output);
  }

  // @@protoc_insertion_point(serialize_end:pb.Purchase)
}

::google::protobuf::uint8* Purchase::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pb.Purchase)
  // bytes claim_hash = 1;
  if (this->claim_hash().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->claim_hash(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pb.Purchase)
  return target;
}

size_t Purchase::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.Purchase)
  size_t total_size = 0;

  // bytes claim_hash = 1;
  if (this->claim_hash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->claim_hash());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Purchase::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.Purchase)
  GOOGLE_DCHECK_NE(&from, this);
  const Purchase* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Purchase>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.Purchase)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.Purchase)
    MergeFrom(*source);
  }
}

void Purchase::MergeFrom(const Purchase& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.Purchase)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.claim_hash().size() > 0) {

    claim_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.claim_hash_);
  }
}

void Purchase::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.Purchase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Purchase::CopyFrom(const Purchase& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.Purchase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Purchase::IsInitialized() const {
  return true;
}

void Purchase::Swap(Purchase* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Purchase::InternalSwap(Purchase* other) {
  claim_hash_.Swap(&other->claim_hash_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Purchase::GetMetadata() const {
  protobuf_purchase_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_purchase_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Purchase

// bytes claim_hash = 1;
void Purchase::clear_claim_hash() {
  claim_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Purchase::claim_hash() const {
  // @@protoc_insertion_point(field_get:pb.Purchase.claim_hash)
  return claim_hash_.GetNoArena();
}
void Purchase::set_claim_hash(const ::std::string& value) {
  
  claim_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.Purchase.claim_hash)
}
#if LANG_CXX11
void Purchase::set_claim_hash(::std::string&& value) {
  
  claim_hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.Purchase.claim_hash)
}
#endif
void Purchase::set_claim_hash(const char* value) {
  
  claim_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.Purchase.claim_hash)
}
void Purchase::set_claim_hash(const void* value, size_t size) {
  
  claim_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.Purchase.claim_hash)
}
::std::string* Purchase::mutable_claim_hash() {
  
  // @@protoc_insertion_point(field_mutable:pb.Purchase.claim_hash)
  return claim_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Purchase::release_claim_hash() {
  // @@protoc_insertion_point(field_release:pb.Purchase.claim_hash)
  
  return claim_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Purchase::set_allocated_claim_hash(::std::string* claim_hash) {
  if (claim_hash != NULL) {
    
  } else {
    
  }
  claim_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), claim_hash);
  // @@protoc_insertion_point(field_set_allocated:pb.Purchase.claim_hash)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)
