// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase.proto

#ifndef PROTOBUF_purchase_2eproto__INCLUDED
#define PROTOBUF_purchase_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace pb {
class Purchase;
class PurchaseDefaultTypeInternal;
extern PurchaseDefaultTypeInternal _Purchase_default_instance_;
}  // namespace pb

namespace pb {

namespace protobuf_purchase_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_purchase_2eproto

// ===================================================================

class Purchase : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.Purchase) */ {
 public:
  Purchase();
  virtual ~Purchase();

  Purchase(const Purchase& from);

  inline Purchase& operator=(const Purchase& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Purchase& default_instance();

  static inline const Purchase* internal_default_instance() {
    return reinterpret_cast<const Purchase*>(
               &_Purchase_default_instance_);
  }

  void Swap(Purchase* other);

  // implements Message ----------------------------------------------

  inline Purchase* New() const PROTOBUF_FINAL { return New(NULL); }

  Purchase* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Purchase& from);
  void MergeFrom(const Purchase& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Purchase* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes claim_hash = 1;
  void clear_claim_hash();
  static const int kClaimHashFieldNumber = 1;
  const ::std::string& claim_hash() const;
  void set_claim_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_claim_hash(::std::string&& value);
  #endif
  void set_claim_hash(const char* value);
  void set_claim_hash(const void* value, size_t size);
  ::std::string* mutable_claim_hash();
  ::std::string* release_claim_hash();
  void set_allocated_claim_hash(::std::string* claim_hash);

  // @@protoc_insertion_point(class_scope:pb.Purchase)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr claim_hash_;
  mutable int _cached_size_;
  friend struct  protobuf_purchase_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Purchase

// bytes claim_hash = 1;
inline void Purchase::clear_claim_hash() {
  claim_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Purchase::claim_hash() const {
  // @@protoc_insertion_point(field_get:pb.Purchase.claim_hash)
  return claim_hash_.GetNoArena();
}
inline void Purchase::set_claim_hash(const ::std::string& value) {
  
  claim_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.Purchase.claim_hash)
}
#if LANG_CXX11
inline void Purchase::set_claim_hash(::std::string&& value) {
  
  claim_hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.Purchase.claim_hash)
}
#endif
inline void Purchase::set_claim_hash(const char* value) {
  
  claim_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.Purchase.claim_hash)
}
inline void Purchase::set_claim_hash(const void* value, size_t size) {
  
  claim_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.Purchase.claim_hash)
}
inline ::std::string* Purchase::mutable_claim_hash() {
  
  // @@protoc_insertion_point(field_mutable:pb.Purchase.claim_hash)
  return claim_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Purchase::release_claim_hash() {
  // @@protoc_insertion_point(field_release:pb.Purchase.claim_hash)
  
  return claim_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Purchase::set_allocated_claim_hash(::std::string* claim_hash) {
  if (claim_hash != NULL) {
    
  } else {
    
  }
  claim_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), claim_hash);
  // @@protoc_insertion_point(field_set_allocated:pb.Purchase.claim_hash)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace pb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_purchase_2eproto__INCLUDED
