// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: support.proto

#ifndef PROTOBUF_support_2eproto__INCLUDED
#define PROTOBUF_support_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace pb {
class Support;
class SupportDefaultTypeInternal;
extern SupportDefaultTypeInternal _Support_default_instance_;
}  // namespace pb

namespace pb {

namespace protobuf_support_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_support_2eproto

// ===================================================================

class Support : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb.Support) */ {
 public:
  Support();
  virtual ~Support();

  Support(const Support& from);

  inline Support& operator=(const Support& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Support& default_instance();

  static inline const Support* internal_default_instance() {
    return reinterpret_cast<const Support*>(
               &_Support_default_instance_);
  }

  void Swap(Support* other);

  // implements Message ----------------------------------------------

  inline Support* New() const PROTOBUF_FINAL { return New(NULL); }

  Support* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Support& from);
  void MergeFrom(const Support& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Support* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string emoji = 1;
  void clear_emoji();
  static const int kEmojiFieldNumber = 1;
  const ::std::string& emoji() const;
  void set_emoji(const ::std::string& value);
  #if LANG_CXX11
  void set_emoji(::std::string&& value);
  #endif
  void set_emoji(const char* value);
  void set_emoji(const char* value, size_t size);
  ::std::string* mutable_emoji();
  ::std::string* release_emoji();
  void set_allocated_emoji(::std::string* emoji);

  // string comment = 2;
  void clear_comment();
  static const int kCommentFieldNumber = 2;
  const ::std::string& comment() const;
  void set_comment(const ::std::string& value);
  #if LANG_CXX11
  void set_comment(::std::string&& value);
  #endif
  void set_comment(const char* value);
  void set_comment(const char* value, size_t size);
  ::std::string* mutable_comment();
  ::std::string* release_comment();
  void set_allocated_comment(::std::string* comment);

  // @@protoc_insertion_point(class_scope:pb.Support)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr emoji_;
  ::google::protobuf::internal::ArenaStringPtr comment_;
  mutable int _cached_size_;
  friend struct  protobuf_support_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Support

// string emoji = 1;
inline void Support::clear_emoji() {
  emoji_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Support::emoji() const {
  // @@protoc_insertion_point(field_get:pb.Support.emoji)
  return emoji_.GetNoArena();
}
inline void Support::set_emoji(const ::std::string& value) {
  
  emoji_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.Support.emoji)
}
#if LANG_CXX11
inline void Support::set_emoji(::std::string&& value) {
  
  emoji_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.Support.emoji)
}
#endif
inline void Support::set_emoji(const char* value) {
  
  emoji_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.Support.emoji)
}
inline void Support::set_emoji(const char* value, size_t size) {
  
  emoji_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.Support.emoji)
}
inline ::std::string* Support::mutable_emoji() {
  
  // @@protoc_insertion_point(field_mutable:pb.Support.emoji)
  return emoji_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Support::release_emoji() {
  // @@protoc_insertion_point(field_release:pb.Support.emoji)
  
  return emoji_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Support::set_allocated_emoji(::std::string* emoji) {
  if (emoji != NULL) {
    
  } else {
    
  }
  emoji_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), emoji);
  // @@protoc_insertion_point(field_set_allocated:pb.Support.emoji)
}

// string comment = 2;
inline void Support::clear_comment() {
  comment_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Support::comment() const {
  // @@protoc_insertion_point(field_get:pb.Support.comment)
  return comment_.GetNoArena();
}
inline void Support::set_comment(const ::std::string& value) {
  
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.Support.comment)
}
#if LANG_CXX11
inline void Support::set_comment(::std::string&& value) {
  
  comment_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pb.Support.comment)
}
#endif
inline void Support::set_comment(const char* value) {
  
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.Support.comment)
}
inline void Support::set_comment(const char* value, size_t size) {
  
  comment_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.Support.comment)
}
inline ::std::string* Support::mutable_comment() {
  
  // @@protoc_insertion_point(field_mutable:pb.Support.comment)
  return comment_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Support::release_comment() {
  // @@protoc_insertion_point(field_release:pb.Support.comment)
  
  return comment_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Support::set_allocated_comment(::std::string* comment) {
  if (comment != NULL) {
    
  } else {
    
  }
  comment_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), comment);
  // @@protoc_insertion_point(field_set_allocated:pb.Support.comment)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace pb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_support_2eproto__INCLUDED
